### ISSUE TITLE
Question: SCL

### ISSUE THREAD

**Issue by manfer** [webtatic-rpms/php54w#1]
Hi,

I have an i686 machine with Centos6.7 installed and the PHP version packaged with the system is 5.3. My intention would be to have other newer versions of PHP globally installed but I don't want to upgrade but have all of them available to choose on different virtual servers being 5.3 the default.

I don't want to build from source because I want my packages managed with the package manager.

Till now I was using SCL but noone is providing a repo with php5.4 SCL packages for i686 that I know, nor for php5.5 nor php5.6. Just x86_64 versions.

I have seen you have i686 packages but no SCL packages at webtatic.

Is it possible to install your packages as SCLs? Should it be preferable to handle different php versions in a different way than SCLs?

Or maybe I'm missing something? I'm confused about the instructions in webtatic. Seems as if I could install any of the versions without overriting the system 5.3 version. But then when I try:

```
$ yum install php54w
...
Error: php54w-common conflicts with php-common-5.3.3-46.el6_6.i686
...
```

Thanks.

**Comment by andytson** [comment]
Hi Fernando,

I had been considering releasing the packages as SCL ones early after SCL was released, however this posed problems for automation of infrastructure provisioning (such as Chef), and Docker was soon released.

The packages have been set so it is possible to build them with SCL enabled, however it'd require some knowledge on how to do so. Some of Webtatic's users do this themselves though.

I consider SCL is really too late in the game, when Docker allows for mixing of multiple containers with even different linux distributions in each. It was in it's infancy at the time, however with the release of several Docker hosting platforms (such as AWS EC2 Container Service, Google Container Engine, and it's open-source software Kubernates), this way of running multiple packages which would otherwise have conflicted is more possible.

I'd consider maintaining SCL packages if there were a good demand for them (or for a fee), however there has been little interest.

**Comment by manfer** [comment]
Thanks for the reply.

So just doing:

```
yum install php54w
yum install php55w
yum install php56w
```

is not enough to install several versions of php in the system. Am I right? That would try to install php5.4 in same place where centos default php version is installed so I would have to uninstall php5.3 version first and then install php5.4, php5.5 or php5.6 as a replacement for the system version, isn't it?

Or otherwise download this repo with the spec file and build the SCL rpms. If I'm not wrong.

Reading the instructions on webtatic it is not clear as it gives some commands that should be executed to replace the system php version as if they were optional commands.

**Comment by manfer** [comment]
Well. I'm going to follow the easier path. I will get rid of php5.3 and install php55w. I really don't need several versions of php on my system so it is not worth to complicate myself.
